apiVersion: v1
kind: Pod 
metadata:
  name: web
  labels:
    app: web
    key: value
spec:
  containers:
    - name: web
      image: lonsedale/homework:12112023
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:1.36
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
